### ISSUE TITLE
dns proxy

### ISSUE THREAD

**Issue by wjlin0** [projectdiscovery/retryabledns#159]
Add support for socks5 proxy for DNS exchanges via `client.ExchangeWithConnContext(...)`

ref: https://github.com/miekg/dns/blob/4d3b87f4ff5ffb7a627638e24bda79f00122ce59/client.go#L192

**Comment by Mzack9999** [comment]
Implemented in 0b895e3c7cc6ef4ed44173d564bae44601838446
