### ISSUE TITLE
QueryMultiple clarification

### ISSUE THREAD

**Issue by gboddin** [projectdiscovery/retryabledns#27]
Hello, first thanks for the great lib !!!!

At https://github.com/projectdiscovery/retryabledns/blob/87dba758f6ee52762c6a332193d073a286bb2dab/client.go#L199 it looks like we break out of QueryMultiple as soon as we have a valid answer, not merging the other answers in the final reply.

Did I miss something or is it expected behavior ?

**Comment by Mzack9999** [comment]
@gboddin Nice catch! This is definitely not the expected behavior, apparently this line was erroneously added within the loop, thanks for reporting it!

**Comment by gboddin** [comment]
Nice thanks !!! I wasn't sure or I would've made the PR.

That's gonna help ipv4/6 resolving :)
