### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by fabaff** [projectdiscovery/retryabledns#8]
It would be nice if a license statement and a LICENSE file is added. Thanks

I need this be able to create a package for Fedora because this is a dependency of another package.

**Comment by ehrishirajsharma** [comment]
Thanks @fabaff. Just added the license file according to the inspired repositories.

**Comment by fabaff** [comment]
As a reference to the Package review: https://bugzilla.redhat.com/show_bug.cgi?id=1839464
